### ISSUE TITLE
Ошибки при запуске приложения

### ISSUE THREAD

**Issue by TatyanaKonysheva** [TatyanaKonysheva/Aqa_3_web#1]
Ошибка возникла 22.06 на предыдущем ДЗ тоже, хотя 21.06 все выполнялось успешно в ДЗ1.2
![image](https://github.com/TatyanaKonysheva/Aqa_3_web/assets/127970375/44d598c3-1389-4792-be3f-91b153798dda).
Переустановила программу, но:
![image](https://github.com/TatyanaKonysheva/Aqa_3_web/assets/127970375/75cbc1cf-0091-4b50-a94f-e0cdc18c3ff3)
![image](https://github.com/TatyanaKonysheva/Aqa_3_web/assets/127970375/e8f5b550-b860-4185-99ef-c43064ef8aaa)

**Comment by andrew-pahomov** [comment]
Не вижу проблем с запуском джарника. В Appveyor он запускается корректно. При локальном запуске в первый раз Вы ошиблись в имени файла, со второго раза также запустили успешно.

**Comment by TatyanaKonysheva** [comment]
Здравствуйте! Извините, за лишнюю панику с моей стороны. Это все от незнания) я уже выполнила ДЗ, но, к сожалению, у меня нет галочки для отправки доработки.

**Comment by TatyanaKonysheva** [comment]
> Не вижу проблем с запуском джарника. В Appveyor он запускается корректно. При локальном запуске в первый раз Вы ошиблись в имени файла, со второго раза также запустили успешно.

Здравствуйте! Извините, за лишнюю панику с моей стороны. Это все от незнания) я уже выполнила ДЗ, но, к сожалению, у меня нет галочки для отправки доработки.

**Comment by TatyanaKonysheva** [comment]
Выполнила в новом репозитории https://github.com/TatyanaKonysheva/Aqa_3_web2. Сборка не проходит. Тесты  при запуске 'gradle clean test' прошли успешно.
